# https://travis-ci.org/tgbugs/ontquery
sudo: false
language: python
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
branches:
  only:
    - master
  git:
    depth: 3

python:
  - 3.6

before_install:
  - sudo apt-get install hunspell
  - sudo apt-get install libhunspell-dev

install:
  - pip install pipenv
  - pipenv install --system --skip-lock
  - pipenv install --dev --system --skip-lock

script:
  - PYTHONWARNINGS=default pipenv run nosetests --with-coverage --cover-tests --cover-package=ontquery

